# Generated by Django 3.2.5 on 2021-07-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=200)),
                ('phone', models.IntegerField(default='')),
            ],
        ),
    ]
