# Generated by Django 3.2.5 on 2021-07-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='photo',
        ),
    ]
